name: X.🏭 [BUILD]

on:
  push:
    branches:
      - "develop" 
      - "release/**" 
  pull_request:
    branches:
      - "main"
      - "develop"

  workflow_dispatch:

jobs:
  build-main:
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Checkout branch 
        uses: actions/checkout@v3
      - name: 📦 Install Packages 
        run: npm i 
      - name: 🏭 Build Project
        run: npm run build
