name: Create PR for Main 

on:
  push:
    branches: 
      - "release/**" 
      - "hotfix/**" 
  pull_request:
    branches:
      - "release/**"

  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: pull-request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automated pr, feature/fix"
          pr_title: "🤖 Merge into main"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body