name: 🤖🐛 [PR] bugfix > develop

on:
  push:
    branches: 
      - "bugfix/**" 

  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Check out repository code
        uses: actions/checkout@v2
      - name: Create pull-request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          pr_label: "bugfix"
          pr_title: "🐛 Bugfix: ${{ github.event.head_commit.message }}"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_draft: true
          github_token: ${{ secrets.GH_PA_TOKEN }}
          # To disable the pull_request from triggering your other workflows, use GITHUB_TOKEN instead
          # github_token: ${{ secrets.GITHUB_TOKEN }}